IBM/platform-services-java-sdk

- build/publish-javadoc.sh
This PR is trying to fix the script used to publish javadocs to gh-pages.
**Fixes:** https://github.ibm.com/arf/planning-sdk-squad/issues/1541
> fix: avoid auth errors during javadoc publish step

- .gitignore
- .travis.yml
- global_catalog.env.enc
- modules/global-catalog/src/test/java/com/ibm/cloud/platform_services/global_catalog/v1/GlobalCatalogIT.java
Includes integration tests for Global Catalog SDK.
> test: add global catalog integration tests

- modules/common/pom.xml
- pom.xml
This PR fixes our bintray deployment issues by using an alternate maven plugin for deployment.
**Fixes:** n/a
> fix(build): use alternate plugin for bintray deployment

- modules/global-search/pom.xml
- modules/global-tagging/pom.xml
- modules/iam-access-groups/pom.xml
- pom.xml
Update java core dependency to 8.1.4, and update some module descriptions.
**Fixes:** n/a
> Update java core

- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsIT.java
Additional changes that reduce the chance of test failures caused by parallel test runs.
- User ids are now unique
- Only old tests that failed to clean up or the current test group are cleaned up.
**Fixes:** https://github.ibm.com/IAM/uum/issues/2348
Integration tests have chances of intermittent failures.
Intermittent failures of integration tests are less likely/fixed.
> test(IAM Access Groups) Additional fixes to reduce integration test failures

- pom.xml
Pulls in a new version of the java-sdk-core dependency.
This new version should fix the "=" issue wrt external config properties.
**Fixes:** n/a
> chore: use new version of the java core

- pom.xml
This PR contains a minor change to pom.xml to avoid problems inside eclipse when performing a "Maven -> Update Project" action.
**Fixes:** n/a
> chore: avoid bintray:deploy issues inside eclipse

- pom.xml
- service-pom.xml
Update java core to v8.2.0
**Fixes:** n/a
> chore: upgrade java core dependency

- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerIT.java
**Fixes:** <! -- link to issue -->
> test: add integration tests for Resource Manager

- build/sync2MC.sh
- pom.xml
This PR changes the bintray-maven-plugin configuration and adds a script used during the build
to sync published artifacts from JCenter to Maven Central.
> fix(build): fix bintray deploy config; add sync script

- .travis.yml
- README.md
- build/sync2MC.sh
- pom.xml
This PR contains changes to synchronize artifacts (jars, poms, etc.) from jcenter to maven central after the "mvn deploy" step within a tagged release build.    The "mvn deploy" step deploys the artifacts to the bintray repository (which in turn publishes them on jcenter), and the "sync2mc" step will synchronize those artifacts from jcenter to maven central.
> chore: sync artifacts to maven central after bintray publish

- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/AccountManagementHelper.java
This PR contains a fix for the EnterpriseManagement integration test code.
> test: use correct date format in AccountManagementHelper

- .travis.yml
Disables int tests for EM and RM services until they can be fixed.
> build: disable EM and RM tests until fixed

- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementIT.java
**Fixes:** <! -- link to issue -->
> Added integration test for Policy and role management service

- .travis.yml
- build/bintraySync.sh
- build/sync2MC.sh
This PR fixes the deployment step by using only a single command.
> build: fix deployment step

- catalog_mgmt.env.enc
- modules/catalog-management/src/test/java/com/ibm/cloud/platform_services/catalog_management/v1/CatalogManagementIT.java
Avoids Github 60 requests per hour throttle for offerings and cleans up catalogs only related to individual tests runs.
> test: harden CM tests

- modules/catalog-management/src/test/java/com/ibm/cloud/platform_services/catalog_management/v1/CatalogManagementIT.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementIT.java
This PR temporarily bypasses some failing integration test methods so we can get a clean build of the master branch.
> test: temporarily bypass failing int test methods

- .travis.yml
- modules/catalog-management/src/test/java/com/ibm/cloud/platform_services/catalog_management/v1/CatalogManagementIT.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementIT.java
Disables integration tests in travis builds due to them being too unreliable.
> Disable its

- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerIT.java
> changed space and app guids

- pom.xml
This PR upgrades the java core dependency to 9.0.1
> build: upgrade java core version to 9.0.1

- modules/case-management/src/test/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagementIT.java
- modules/catalog-management/src/test/java/com/ibm/cloud/platform_services/catalog_management/v1/CatalogManagementIT.java
This PR contains minor fixes to the case-mgmt and catalog-mgmt integration tests.
> test: fix case-mgmt and catalog-mgmt integration tests

- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/UserManagement.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/InviteUserIamPolicy.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/UserManagementTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/AttributeTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/GetUserProfileOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/GetUserSettingsOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/InviteUserIamPolicyTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/InviteUserTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/InviteUsersOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/ListUsersOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/RemoveUsersOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/ResourceTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/RoleTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/UpdateUserProfilesOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/UpdateUserSettingsOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/UserListTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/UserProfileTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/UserSettingsTest.java
This PR contains a re-gen of the User Management service.
> fix(User Management): added 'type' property to InviteUserIamPolicy class

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentity.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityIT.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityTest.java
- modules/open-service-broker/src/test/java/com/ibm/cloud/platform_services/open_service_broker/v1/OpenServiceBrokerIT.java
- pom.xml
This PR contains a re-gen of the IAM Identity service after recent API definition updates.
> fix(IAM Identity): re-gen service after API definition updates

- README.md
- modules/coverage-reports/pom.xml
- modules/enterprise-usage-reports/pom.xml
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReports.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/GetResourceUsageReportOptions.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/Link.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/MetricUsage.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/PlanUsage.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/Reports.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsage.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsageReport.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/package-info.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsIT.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/GetResourceUsageReportOptionsTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/LinkTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/MetricUsageTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/PlanUsageTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ReportsTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsageReportTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsageTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/utils/TestUtilities.java
- modules/examples/pom.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsExamples.java
- pom.xml
This PR adds the Enterprise Usage Reports service to the project, including integration tests and examples.
> feat(Enterprise Usage Reports): add service to project

- pom.xml
> build: upgrade java core to 9.5.1

- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernance.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateAttachmentsOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateRulesOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/DeleteAttachmentOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/DeleteRuleOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/EnforcementAction.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/GetAttachmentOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/GetRuleOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListAttachmentsOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListRulesOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/Rule.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/RuleCondition.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/RuleConditionSingleProperty.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/RuleRequiredConfig.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/RuleRequiredConfigSingleProperty.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/RuleSingleProperty.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/RuleTargetAttribute.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/TargetResource.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateAttachmentOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateRuleOptions.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceIT.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateAttachmentsOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateRulesOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListRulesOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateAttachmentOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateRuleOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/utils/TestUtilities.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceExamples.java
Updates Configuration Governance service after recent API changes
> fix(Configuration Governance): update service after API changes

- modules/examples/pom.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsExamples.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroups.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/AccountSettings.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/AddGroupMembersResponseMembersItem.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/Group.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListGroupMembersResponseMember.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/Rule.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsIT.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/utils/TestUtilities.java
- pom.xml
Updates the IAM Access Groups service after recent API changes, and adds working examples to the project.
> fix(IAM Access Groups): regen service and add examples

- modules/case-management/src/test/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagementIT.java
- modules/catalog-management/src/test/java/com/ibm/cloud/platform_services/catalog_management/v1/CatalogManagementIT.java
- modules/common/src/test/java/com/ibm/cloud/platform_services/test/SdkIntegrationTestBase.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceIT.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagementIT.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsIT.java
- modules/global-catalog/src/test/java/com/ibm/cloud/platform_services/global_catalog/v1/GlobalCatalogIT.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchIT.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTaggingIT.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsIT.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityIT.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementIT.java
- modules/open-service-broker/src/test/java/com/ibm/cloud/platform_services/open_service_broker/v1/OpenServiceBrokerIT.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerIT.java
- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerIT.java
- modules/usage-reports/src/test/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReportsIT.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/UserManagementIT.java
Updates to integration tests to make logging more consistent.
> test: use consistent logging in int tests

- .travis.yml
This PR changes the build to:
1. avoid the default "mvn install" step that occurs when a java build does not specify the "install" section.
2. parallelize each artifact's syncing to maven central to avoid excessive build times.
> Additional build improvements

- .travis.yml
- build/setupSigning.sh
- modules/examples/pom.xml
- pom.xml
More fixes for the maven central deployment part of the build
> fix(build): fix maven central deploy problems

- .travis.yml
- build/setupSigning.sh
- pom.xml
> fix(build): revert to using gnupg 1.x

- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/UserManagement.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/Attribute.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/InvitedUser.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/InvitedUserList.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/ListUsersOptions.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/RemoveUserOptions.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/Resource.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/UpdateUserProfileOptions.java
- modules/user-management/src/main/java/com/ibm/cloud/platform_services/user_management/v1/model/UserList.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/UserManagementIT.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/UserManagementTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/InvitedUserListTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/InvitedUserTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/RemoveUserOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/model/UpdateUserProfileOptionsTest.java
- modules/user-management/src/test/java/com/ibm/cloud/platform_services/user_management/v1/utils/TestUtilities.java
This PR contains a re-gen of the User Management service after recent API changes, plus some updates to the integration test.
> fix(User Management): re-gen service and update tests after API changes

- README.md
- modules/coverage-reports/pom.xml
- modules/examples/pom.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMeteringExamples.java
- modules/usage-metering/pom.xml
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMetering.java
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/model/MeasureAndQuantity.java
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ReportResourceUsageOptions.java
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ResourceInstanceUsage.java
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ResourceUsageDetails.java
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ResponseAccepted.java
- modules/usage-metering/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/package-info.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMeteringIT.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMeteringTest.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/model/MeasureAndQuantityTest.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ReportResourceUsageOptionsTest.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ResourceInstanceUsageTest.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ResourceUsageDetailsTest.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/model/ResponseAcceptedTest.java
- modules/usage-metering/src/test/java/com/ibm/cloud/platform_services/usage_metering/v4/utils/TestUtilities.java
- pom.xml
This PR adds the Usage Metering service to the project.
> feat(Usage Metering): add service to project

- modules/case-management/src/main/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagement.java
- modules/case-management/src/main/java/com/ibm/cloud/platform_services/case_management/v1/model/Attachment.java
- modules/case-management/src/main/java/com/ibm/cloud/platform_services/case_management/v1/model/Comment.java
- modules/case-management/src/test/java/com/ibm/cloud/platform_services/case_management/v1/utils/TestUtilities.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernance.java
- modules/enterprise-billing-units/src/main/java/com/ibm/cloud/platform_services/enterprise_billing_units/v1/EnterpriseBillingUnits.java
- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagement.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/utils/TestUtilities.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReports.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/utils/TestUtilities.java
- modules/examples/pom.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchExamples.java
- modules/global-catalog/src/main/java/com/ibm/cloud/platform_services/global_catalog/v1/GlobalCatalog.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearch.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/model/ScanResult.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchIT.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/utils/TestUtilities.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTagging.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/utils/TestUtilities.java
This PR contains a re-gen of several services along with new examples for the Global Search service.
> re-gen services and add examples

- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernance.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateAttachmentsOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateRulesOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/DeleteAttachmentOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/DeleteRuleOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/GetAttachmentOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/GetRuleOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListAttachmentsOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListRulesOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateAttachmentOptions.java
- modules/configuration-governance/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateRuleOptions.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateAttachmentsOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/CreateRulesOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/DeleteAttachmentOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/DeleteRuleOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/GetAttachmentOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/GetRuleOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListAttachmentsOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/ListRulesOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateAttachmentOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/model/UpdateRuleOptionsTest.java
- modules/configuration-governance/src/test/java/com/ibm/cloud/platform_services/configuration_governance/v1/utils/TestUtilities.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceExamples.java
**Fixes:** <! -- link to issue -->
> fix(Configuration Governance): re-gen service after recent API changes

- modules/case-management/src/test/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagementIT.java
This PR fixes some minor issues in the case-mgmt integration test.
> test(Case Management): minor fixes to case-mgmt int test

- pom.xml
Upgrades java core dependency to 9.8.0
> fix(build): upgrade java core to v9.8.0

- .github/pull_request_template.md
- modules/examples/src/main/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_billing_units/v1/EnterpriseBillingUnitsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_catalog/v1/GlobalCatalogExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTaggingExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/open_service_broker/v1/OpenServiceBrokerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMeteringExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReportsExamples.java
Fixes up comments in the examples classes.
> chore: fix-up config comments in examples

- modules/examples/pom.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerExamples.java
- modules/resource-manager/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManager.java
- modules/resource-manager/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/model/ListResourceGroupsOptions.java
- modules/resource-manager/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/model/ResCreateResourceGroup.java
- modules/resource-manager/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/model/ResourceGroup.java
- modules/resource-manager/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/model/ResourceQuota.java
- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerIT.java
- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerTest.java
- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/model/ListResourceGroupsOptionsTest.java
- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/model/QuotaDefinitionListTest.java
- modules/resource-manager/src/test/java/com/ibm/cloud/platform_services/resource_manager/v2/model/ResourceGroupListTest.java
This PR updates the Resource Manager service, adds examples and move configuration values out from test calss into configuration file.
> fix(Resource Manager): update service after recent API changes and generate examples

- modules/examples/src/main/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_billing_units/v1/EnterpriseBillingUnitsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_catalog/v1/GlobalCatalogExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTaggingExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/open_service_broker/v1/OpenServiceBrokerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMeteringExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReportsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/user_management/v1/UserManagementExamples.java
This PR adds the following:
- labels to examples, so it is possible to identify which output section belongs to which method when examples are run
- it also replaces "\n" to "%n" in printf methods. "%n" is platform indepented new-line character
> fix: add labels to service examples

- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearch.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/model/SupportedTypesList.java
> fix(global search): update global search service sdk after api changes

- checkstyle.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerExamples.java
- pom.xml
This PR modifies the Resource Controller working examples so that the labels displayed in the output will not be included in the API reference.
> chore: hide labels from API reference

- CODE_OF_CONDUCT.md
- pom.xml
Upgrade java core to the most recent version
> fix(deps): upgrade java core version

- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagement.java
- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/package-info.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagementTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/ListAccountGroupsOptionsTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/ListAccountsOptionsTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/ListEnterprisesOptionsTest.java
Re-gen of service after API changes.
> fix(Enterprise Management): update service after API changes

- .secrets.baseline
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerExamples.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceController.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceAliasesForInstanceOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceAliasesOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceBindingsForAliasOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceBindingsOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceInstancesOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceKeysForInstanceOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceKeysOptions.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/package-info.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerIT.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceAliasesForInstanceOptionsTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceAliasesOptionsTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceBindingsForAliasOptionsTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceBindingsOptionsTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceInstancesOptionsTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceKeysForInstanceOptionsTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceKeysOptionsTest.java
This PR updates the Resource Controller service, integration tests and examples.
> fix(Resource Controller): update service after recent API changes

- modules/examples/src/main/java/com/ibm/cloud/platform_services/case_management/v1/CaseManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/configuration_governance/v1/ConfigurationGovernanceExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_billing_units/v1/EnterpriseBillingUnitsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_catalog/v1/GlobalCatalogExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTaggingExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/open_service_broker/v1/OpenServiceBrokerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/posture_management/v1/PostureManagementExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/resource_manager/v2/ResourceManagerExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_metering/v4/UsageMeteringExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReportsExamples.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/user_management/v1/UserManagementExamples.java
> Fix example labels

- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentity.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/AccountSettingsResponse.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UpdateAccountSettingsOptions.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityIT.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/AccountSettingsResponseTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UpdateAccountSettingsOptionsTest.java
This PR contains the re-generated IAM Identity service and the updated integration tests.
> fix(IAM Identity): update service after recent API changes

- pom.xml
This PR upgrades our java core dependency to version 9.10.1
> build: upgrade java core to 9.10.1

- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceController.java
- modules/resource-controller/src/main/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceInstancesOptions.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/ResourceControllerTest.java
- modules/resource-controller/src/test/java/com/ibm/cloud/platform_services/resource_controller/v2/model/ListResourceInstancesOptionsTest.java
PR for resource controller service update and integration test changes
> fix(Resource Controller): update service after api changes

- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentity.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ServiceId.java
> fix(IAM Identity): re-gen service after recent API changes

- pom.xml
This PR upgrades our java core dependency to version 9.10.3, and our okhttp3 dependency to version 4.9.1
> build: upgrade java core and okhttp3 dependencies

- README.md
- modules/coverage-reports/pom.xml
- modules/examples/pom.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/IbmCloudShellExamples.java
- modules/ibm-cloud-shell/pom.xml
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/IbmCloudShell.java
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/AccountSettings.java
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/Feature.java
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/GetAccountSettingsOptions.java
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/RegionSetting.java
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/UpdateAccountSettingsOptions.java
- modules/ibm-cloud-shell/src/main/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/package-info.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/IbmCloudShellIT.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/IbmCloudShellTest.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/AccountSettingsTest.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/FeatureTest.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/GetAccountSettingsOptionsTest.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/RegionSettingTest.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/model/UpdateAccountSettingsOptionsTest.java
- modules/ibm-cloud-shell/src/test/java/com/ibm/cloud/platform_services/ibm_cloud_shell/v1/utils/TestUtilities.java
- pom.xml
> feat(Cloudshell): add service, tests and examples to project

- pom.xml
> chore: upgrade java sdk core version

- pom.xml
This PR bumps the java core version to 9.12.1 to pull in the ContainerAuthenticator functionality.
> fix: bump java core version to 9.12.1

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
> docs:  fix documentation

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentity.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ListLinksOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ListProfilesOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ProfileClaimRuleConditions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ServiceId.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/package-info.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityIT.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/CreateApiKeyOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/CreateServiceIdOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetAccountSettingsOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetApiKeyOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetApiKeysDetailsOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetServiceIdOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ListApiKeysOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ListLinksOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ListProfilesOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ListServiceIdsOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UpdateAccountSettingsOptionsTest.java
> feat(iam-identity): fixing examples

- .travis.yml
- build/setupSigning.sh
Bumps up our node version to 14 to accommodate semantic-release v18.
> chore(build): use node 14 with new semantic-release version

- .travis.yml
- pom.xml
Bumps the maven gpg plugin to the most recent in hopes of fixing the recent problems with the gpg signing step where gpg is asking for a passphrase during the maven build on travis :(
> fix(build): use latest maven gpg plugin

- pom.xml
Bumps the version of a few dependencies to avoid CRA code scanning vulnerability alerts.
> build: bump dependencies to avoid vulnerability alerts

- pom.xml
This PR upgrades our java core dependency to 9.14.1 to pull in the newer gson which addresses a security vulnerability.
> fix: bump java core version to 9.14.1

- .secrets.baseline
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroups.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/DeleteAccessGroupOptionsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/GetAccessGroupOptionsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListAccessGroupMembersOptionsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListAccessGroupsOptionsTest.java
- pom.xml
This PR updates the IAM Access Groups SDK code after the API definition was modified to move the "/v2" path segment from the service URL to each individual path.
> fix(IAM Access Groups): update service after service url adjustment

- pom.xml
This PR bumps the java core version to the latest
> fix: bump java core to 9.15.2

- .secrets.baseline
- pom.xml
This PR bumps our java core dependency to 9.15.5
> fix: bump java core to 9.15.5

- pom.xml
This PR bumps the java core dependency to 9.16.0.
> build: bump java core to 9.16.0

- pom.xml
Bumps the java core version to 9.16.1, plus updates a few other dependencies as well.
> build: bump core to 9.16.1

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsExamples.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroups.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/AddGroupMembersRequestMembersItem.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/Group.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListAccessGroupMembersOptions.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListAccessGroupsOptions.java
- modules/iam-access-groups/src/main/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListGroupMembersResponseMember.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsIT.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/IamAccessGroupsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/GroupTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListAccessGroupMembersOptionsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListAccessGroupsOptionsTest.java
- modules/iam-access-groups/src/test/java/com/ibm/cloud/platform_services/iam_access_groups/v2/model/ListGroupMembersResponseMemberTest.java
This PR upates the membership_type in the sdk
> feat(IAM Access Groups): add support for dynamic membership

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityTest.java
> test(IAM Identity): update examples with right tags

- pom.xml
This PR bumps the java core dependency to avoid a vulnerability
in the kotlin-stdlib dependency
> fix: bump java core to avoid kotlin-stdlib vulnerability

- pom.xml
This PR just bumps up the java core version to 9.17.2 and okhttp to 4.9.3
> fix: bump core version to 9.17.2

- pom.xml
This PR bumps the versions of the java core and okhttp3 dependencies to avoid a CVE.
> fix: bump core and okhttp3 to avoid CVE

- modules/examples/src/main/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictionsExamples.java
Signed-off-by: Stephen SooHoo <soohoos@us.ibm.com>
Better SDK example alignment with curl examples.
> refactor(Context-based Restrictions): update create zone examples

- pom.xml
This PR bumps the version of several dependencies in an attempt to stay current.
Signed-off-by: Phil Adams <phil_adams@us.ibm.com>
> build: bump dependency versions

- .secrets.baseline
Updates the .secrets.baseline file to avoid warnings from our scanning jobs.
> build: update .secrets.baseline to avoid warnings

- .travis.yml
- pom.xml
Some build-related changes to allow us to build/test the project on java 9, 11, 17, etc.
> build: allow build/test on java9+

- modules/context-based-restrictions/src/main/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictions.java
- modules/context-based-restrictions/src/main/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/model/ListRulesOptions.java
- modules/context-based-restrictions/src/test/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictionsIT.java
- modules/context-based-restrictions/src/test/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictionsTest.java
- modules/context-based-restrictions/src/test/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/model/ListRulesOptionsTest.java
Signed-off-by: Cameron Davis <cjdavis@ibm.com>
This PR adds CBR support for the new service_group_id parameter in rules.
No current behavior should be modified. Adds the further control to be able to apply rules to service groups
> add test for list rule with service group id

- .secrets.baseline
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReports.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/GetResourceUsageReportOptions.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/GetResourceUsageReportPager.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/Link.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/MetricUsage.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/PlanUsage.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/Reports.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsage.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsageReport.java
- modules/enterprise-usage-reports/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/package-info.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsIT.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/GetResourceUsageReportOptionsTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/LinkTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/MetricUsageTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/PlanUsageTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ReportsTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsageReportTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/model/ResourceUsageTest.java
- modules/enterprise-usage-reports/src/test/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/utils/TestUtilities.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/enterprise_usage_reports/v1/EnterpriseUsageReportsExamples.java
This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.
Signed-off-by: Phil Adams <phil_adams@us.ibm.com>
> fix(Enterprise Usage Reports): regen service to get Pager

- pom.xml
Bump java core to latest version (9.17.4).
> build: bump java core to latest version

- .cra/.cveignore
This PR ignores the testng vulnerability false positive
> build: ignore testng vulnerability false positive

- checkstyle.xml
- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentity.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/AccountBasedMfaEnrollment.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/CreateMfaReportOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetMfaReportOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetMfaStatusOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/IdBasedMfaEnrollment.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/MfaEnrollmentTypeStatus.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/MfaEnrollments.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ReportMfaEnrollmentStatus.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UserMfaEnrollments.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UserReportMfaEnrollmentStatus.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityIT.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/AccountBasedMfaEnrollmentTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/CreateMfaReportOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetMfaReportOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetMfaStatusOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/IdBasedMfaEnrollmentTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/MfaEnrollmentTypeStatusTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/MfaEnrollmentsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ReportMfaEnrollmentStatusTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UpdateAccountSettingsOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UserMfaEnrollmentsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UserReportMfaEnrollmentStatusTest.java
Java SDK doc for IAM identity. PR includes changes related
1. Create mfa report
2. Get mfa report
3. Get mfa user status
4.  Change token expiration max and default value to 259200
> fix(IAM Identity): re-gen with latest API definition

- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountOptions.java
- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountRequestTraits.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagementTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountRequestTraitsTest.java
Trait object schema change in create account request object.
> feat(Enterprise management):change in trait object schema

- service-pom.xml
This commit is being merged in simply to force a
new minor version to be published.
This is being done because a previously-merged
commit was mis-labeled and didn't automatically
trigger a new release.
> feat(build): force new version to be published

- modules/usage-reports/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/model/AccountSummary.java
- modules/usage-reports/src/main/java/com/ibm/cloud/platform_services/usage_reports/v4/model/Plan.java
- modules/usage-reports/src/test/java/com/ibm/cloud/platform_services/usage_reports/v4/UsageReportsTest.java
- modules/usage-reports/src/test/java/com/ibm/cloud/platform_services/usage_reports/v4/model/AccountSummaryTest.java
- modules/usage-reports/src/test/java/com/ibm/cloud/platform_services/usage_reports/v4/model/PlanTest.java
Updates Account Summary to reflect changes to the API
Updates Account Summary to reflect changes to the API
Tests:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] IBM Cloud Platform Services Java SDK 99-SNAPSHOT ... SUCCESS [ 27.608 s]
[INFO] IBM Cloud Platform Services SDK Common Library ..... SUCCESS [ 24.271 s]
[INFO] IBM Cloud Case Management API ...................... SUCCESS [ 31.055 s]
[INFO] IBM Cloud Catalog Management API ................... SUCCESS [ 44.613 s]
[INFO] IBM Cloud Context-Based Restrictions API ........... SUCCESS [ 27.531 s]
[INFO] IBM Cloud Enterprise Billing Units API ............. SUCCESS [ 23.684 s]
[INFO] IBM Cloud Enterprise Management API ................ SUCCESS [ 25.708 s]
[INFO] IBM Cloud …
```
> feat(Usage Reports): Update Account Summary

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityExamples.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentity.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/AccountSettingsResponse.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/AccountSettingsUserMFA.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/DeleteProfileIdentityOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetProfileIdentitiesOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetProfileIdentityOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/IdBasedMfaEnrollment.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ProfileIdentitiesResponse.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ProfileIdentity.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ProfileLink.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/SetProfileIdentitiesOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/SetProfileIdentityOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/model/UpdateAccountSettingsOptions.java
- modules/iam-identity/src/main/java/com/ibm/cloud/platform_services/iam_identity/v1/package-info.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityIT.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/IamIdentityTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/DeleteProfileIdentityOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetProfileIdentitiesOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/GetProfileIdentityOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ProfileIdentitiesResponseTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/ProfileIdentityTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/SetProfileIdentitiesOptionsTest.java
- modules/iam-identity/src/test/java/com/ibm/cloud/platform_services/iam_identity/v1/model/SetProfileIdentityOptionsTest.java
Added feature support for Trusted Profile identities work, add, get, delete identities associated with the profile. 
SDK adopters will be able to call Trusted profile identities APIs.
API defintion:
[Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api?code=java#get-profile-identities)
Test information:
Integration Tests:
```sh
PASSED: com.ibm.cloud.platform_services.iam_identity.v1.IamIdentityIT.testGetReportMfaComplete
PASSED: com.ibm.cloud.platform_services.iam_identity.v1.IamIdentityIT.testDeleteApiKey1
PASSED: com.ibm.cloud.platform_services.iam_identity.v1.IamIdentityIT.testCreateServiceIdNegative
PASSED: com.ibm.cloud.platform_services.iam_identity.v1.IamIdentityIT.testGetApiKeysDetails
PASSED: …
```
> feat(IAM Identity): add trusted profile identities api

- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountOptions.java
- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountRequestTraits.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagementTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountOptionsTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountRequestTraitsTest.java
re-gen service after update trait object
> feat(Enterprise Management): re-gen service after update trait object

- pom.xml
Removes some obsolete configuration from the pom.xml file.
> build: remove obsolete config from pom.xml

- CONTRIBUTING.md
- update_service.md
This PR updates some documentation to include info for devs using Windows.
> docs: add windows instructions to docs

- pom.xml
Bump dependency versions as needed to avoid CVEs.
> fix: bump dependencies to avoid CVEs

- modules/examples/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementExamples.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagement.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/LimitData.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/PolicyTemplateLimitData.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/RuleAttributeWithConditions.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/TemplateCountData.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/V2PolicyRule.java
- modules/iam-policy-management/src/main/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/V2PolicyRuleRuleWithConditions.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementIT.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/IamPolicyManagementTest.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/LimitDataTest.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/PolicyTemplateLimitDataTest.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/RuleAttributeWithConditionsTest.java
- modules/iam-policy-management/src/test/java/com/ibm/cloud/platform_services/iam_policy_management/v1/model/TemplateCountDataTest.java
Updated based on API definition fix to allow for `conditions` under `rule.conditions`.
Tests:
Examples:
```sh
mvn exec:java -Dexec.mainClass="com.ibm.cloud.platform_services.iam_policy_management.v1.IamPolicyManagementExamples" ... [INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.119 s
[INFO] Finished at: 2023-10-30T16:23:38-04:00
[INFO] ------------------------------------------------------------------------
```
mvn clean install:
```sh
mvn clean install ... [INFO] Reactor Summary for IBM Cloud Platform Services Java SDK 99-SNAPSHOT:
[INFO] 
[INFO] IBM Cloud Platform Services Java SDK ............... SUCCESS [  9.402 s]
[INFO] IBM …
```
> fix(IAM Policy Management): Added nest conditions to rule.conditions

- modules/context-based-restrictions/src/main/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictions.java
- modules/context-based-restrictions/src/main/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/model/APIType.java
- modules/context-based-restrictions/src/test/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictionsTest.java
- modules/context-based-restrictions/src/test/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/model/APITypeTest.java
- modules/examples/src/main/java/com/ibm/cloud/platform_services/context_based_restrictions/v1/ContextBasedRestrictionsExamples.java
- add new field to /v1/operations response
- fix zone example values
- support /v1/operations 'enforcement_modes' response field
- add IPv6 examples for doc/SDK consistency
> feat(Context-Based Restrictions): add enforcement_modes to operations response

- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearch.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTagging.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/model/AttachTagOptions.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/model/CreateTagOptions.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/model/DeleteTagAllOptions.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/model/DeleteTagOptions.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/model/DetachTagOptions.java
- modules/global-tagging/src/main/java/com/ibm/cloud/platform_services/global_tagging/v1/model/ListTagsOptions.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/GlobalTaggingTest.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/model/AttachTagOptionsTest.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/model/CreateTagOptionsTest.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/model/DeleteTagAllOptionsTest.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/model/DeleteTagOptionsTest.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/model/DetachTagOptionsTest.java
- modules/global-tagging/src/test/java/com/ibm/cloud/platform_services/global_tagging/v1/model/ListTagsOptionsTest.java
> fix(Global Tagging): regenerate service using latest API definition

- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearch.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/model/ResultItem.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/model/ScanResult.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/model/SearchOptions.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/package-info.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchTest.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/model/ResultItemTest.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/model/ScanResultTest.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/model/SearchOptionsTest.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/utils/TestUtilities.java
New documentation about `replace` on get-tags swagger
> fix(Global Search/Tagging): re-gen services with latest API definition

- CHANGELOG.md
This is a "do nothing" PR to fix a prior commit message so that a new version of the project is published.
> fix(Global Search/Tagging): regen services with latest API definition

- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagement.java
- modules/enterprise-management/src/main/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountResponse.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/EnterpriseManagementTest.java
- modules/enterprise-management/src/test/java/com/ibm/cloud/platform_services/enterprise_management/v1/model/CreateAccountResponseTest.java
Re-Generated sdk after recent create_account response changes in create enterprise child account api
> fix(Enterprise Management): re-gen service after recent create_account response changes

- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearch.java
- modules/global-search/src/main/java/com/ibm/cloud/platform_services/global_search/v2/model/SearchOptions.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/GlobalSearchTest.java
- modules/global-search/src/test/java/com/ibm/cloud/platform_services/global_search/v2/model/SearchOptionsTest.java
Updated documentation about project onboarding
> fix(Global Search): add support for is_project_resource query param

- .github/workflows/build.yaml
- .github/workflows/publish.yaml
- .secrets.baseline
- pom.xml
Enable github actions for CI/CD.
> fix: enable github workflows
